/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.toggle.scenarios;

import com.anfelisa.todo.data.ToggleTodoResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class ToggleTodoTwiceScenario extends AbstractToggleTodoTwiceScenario {

	

}




/******* S.D.G. *******/



