/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.toggle.scenarios;

public class ToggleTodoScenario extends AbstractToggleTodoScenario {

	

}




/******* S.D.G. *******/



