/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




package com.anfelisa.todo.createcategory.scenarios;

import com.anfelisa.todo.data.CreateCategoryResponse;

@SuppressWarnings("unused")
public class CreateCategoryScenario extends AbstractCreateCategoryScenario {

	

}




/******* S.D.G. *******/



