/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.get.scenarios;

public class GetTodoJsonScenario extends AbstractGetTodoJsonScenario {

	

}




/******* S.D.G. *******/



