/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.get.scenarios;

@SuppressWarnings("unused")
public class GetTodoScenario extends AbstractGetTodoScenario {

	

}




/******* S.D.G. *******/



