/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




package com.anfelisa.todo.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TodoListData extends AbstractTodoListData implements ITodoListData {
	
	public TodoListData(
		@JsonProperty("todoList") java.util.List<com.anfelisa.todo.models.ITodoModel> todoList, 
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			todoList,
			categoryId,
			uuid
		);
	}

	public TodoListData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.todo.models.ITodoListModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.todo.models.ITodoListModel testData = new com.anfelisa.todo.models.TodoListModel();
		java.util.List<com.anfelisa.todo.models.ITodoModel> todoListList = new java.util.ArrayList<com.anfelisa.todo.models.ITodoModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			todoListList.add(com.anfelisa.todo.data.TodoData.generateTestData());
		}
		testData.setTodoList(todoListList);
		testData.setCategoryId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



