/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




package com.anfelisa.todo.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TodoData extends AbstractTodoData implements ITodoData {
	
	public TodoData(
		@JsonProperty("id") String id, 
		@JsonProperty("description") String description, 
		@JsonProperty("done") Boolean done, 
		@JsonProperty("createdDateTime") java.time.LocalDateTime createdDateTime, 
		@JsonProperty("updatedDateTime") java.time.LocalDateTime updatedDateTime, 
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			id,
			description,
			done,
			createdDateTime,
			updatedDateTime,
			categoryId,
			uuid
		);
	}

	public TodoData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.todo.models.ITodoModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.todo.models.ITodoModel testData = new com.anfelisa.todo.models.TodoModel();
		testData.setId(randomString(random));
		testData.setDescription(randomString(random));
		testData.setDone(random.nextBoolean());
		testData.setCreatedDateTime(random.nextBoolean() ? java.time.LocalDateTime.now().plusMinutes(random.nextInt(60)) : java.time.LocalDateTime.now().minusMinutes(random.nextInt(60)) );
		testData.setUpdatedDateTime(random.nextBoolean() ? java.time.LocalDateTime.now().plusMinutes(random.nextInt(60)) : java.time.LocalDateTime.now().minusMinutes(random.nextInt(60)) );
		testData.setCategoryId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



