/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




package com.anfelisa.todo.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ToggleAllData extends AbstractToggleAllData implements IToggleAllData {
	
	public ToggleAllData(
		@JsonProperty("done") Boolean done, 
		@JsonProperty("todosToBeToggled") java.util.List<com.anfelisa.todo.models.ITodoModel> todosToBeToggled, 
		@JsonProperty("updatedDateTime") java.time.LocalDateTime updatedDateTime, 
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			done,
			todosToBeToggled,
			updatedDateTime,
			categoryId,
			uuid
		);
	}

	public ToggleAllData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.todo.models.IToggleAllModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.todo.models.IToggleAllModel testData = new com.anfelisa.todo.models.ToggleAllModel();
		testData.setDone(random.nextBoolean());
		java.util.List<com.anfelisa.todo.models.ITodoModel> todosToBeToggledList = new java.util.ArrayList<com.anfelisa.todo.models.ITodoModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			todosToBeToggledList.add(com.anfelisa.todo.data.TodoData.generateTestData());
		}
		testData.setTodosToBeToggled(todosToBeToggledList);
		testData.setUpdatedDateTime(random.nextBoolean() ? java.time.LocalDateTime.now().plusMinutes(random.nextInt(60)) : java.time.LocalDateTime.now().minusMinutes(random.nextInt(60)) );
		testData.setCategoryId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



