database:
  driverClass: org.sqlite.JDBC
  user: admin
  password: 
  url: jdbc:sqlite:todo.db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 3s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 1
  maxSize: 1
  initialSize: 1
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  
server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8096
  adminConnectors:
    - type: http
      port: 8097

config:
  mode: DEV
  writeTimeline: ALWAYS
