/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.update.scenarios;

import com.anfelisa.todo.data.UpdateTodoResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class UpdateTodoScenario extends AbstractUpdateTodoScenario {

	

}




/******* S.D.G. *******/



