/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.update.scenarios;

public class UpdateTodoScenario extends AbstractUpdateTodoScenario {

	

}




/******* S.D.G. *******/



