/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.toggle.all.scenarios;

import com.anfelisa.todo.data.ToggleAllResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class ToggleAllWhenOneIsDoneExpectAllToBeDoneScenario extends AbstractToggleAllWhenOneIsDoneExpectAllToBeDoneScenario {

	

}




/******* S.D.G. *******/



