/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.toggle.all.scenarios;

public class ToggleAllWhenOneIsDoneExpectAllToBeDoneScenario extends AbstractToggleAllWhenOneIsDoneExpectAllToBeDoneScenario {

	

}




/******* S.D.G. *******/



