/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.toggle.all.scenarios;

public class ToggleAllWhenAllAreDoneExpectAllToBeOpenScenario extends AbstractToggleAllWhenAllAreDoneExpectAllToBeOpenScenario {

	

}




/******* S.D.G. *******/



