/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.clear.done.scenarios;

import de.acegen.HttpResponse;

@SuppressWarnings("unused")
public class ClearDoneScenario extends AbstractClearDoneScenario {

	

}




/******* S.D.G. *******/



