/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.clear.done.scenarios;

import com.anfelisa.todo.data.ToggleAllResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class ClearDoneScenario extends AbstractClearDoneScenario {

	

}




/******* S.D.G. *******/



