/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.todo.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.todo.data.IClearDoneData;
import com.anfelisa.todo.models.ICategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ClearDoneCommand extends AbstractClearDoneCommand {

	static final Logger LOG = LoggerFactory.getLogger(ClearDoneCommand.class);

	public ClearDoneCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IClearDoneData executeCommand(IClearDoneData data, PersistenceHandle readonlyHandle) {
		ICategoryModel categoryModel = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getCategoryId());
		if (categoryModel == null) {
			this.throwIllegalArgumentException("category " + data.getCategoryId() + " does not exist.");
		}
		this.addSuccessOutcome(data);
		return data;
	}

}

/******* S.D.G. *******/
