/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.todo.commands;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.todo.data.IToggleAllData;
import com.anfelisa.todo.models.ICategoryModel;
import com.anfelisa.todo.models.ITodoModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ToggleAllCommand extends AbstractToggleAllCommand {

	static final Logger LOG = LoggerFactory.getLogger(ToggleAllCommand.class);

	public ToggleAllCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IToggleAllData executeCommand(IToggleAllData data, PersistenceHandle readonlyHandle) {
		ICategoryModel categoryModel = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getCategoryId());
		if (categoryModel == null) {
			this.throwIllegalArgumentException("category " + data.getCategoryId() + " does not exist.");
		}
		data.setUpdatedDateTime(data.getSystemTime());
		List<ITodoModel> todos = daoProvider.getTodoDao().selectAllOfCategory(readonlyHandle, data.getCategoryId());
		List<ITodoModel> open = new ArrayList<>();
		boolean allAreDone = true;
		for (ITodoModel todo : todos) {
			if (todo.getDone() == false) {
				allAreDone = false;
				open.add(todo);
			}
		}
		data.setDone(!allAreDone);
		if (allAreDone) {
			data.setTodosToBeToggled(todos);
		} else {
			data.setTodosToBeToggled(open);
		}
		this.addSuccessOutcome(data);
		return data;
	}

}

/******* S.D.G. *******/
