/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.todo.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.todo.data.ITodoToggleData;
import com.anfelisa.todo.models.ITodoModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ToggleTodoCommand extends AbstractToggleTodoCommand {

	static final Logger LOG = LoggerFactory.getLogger(ToggleTodoCommand.class);

	public ToggleTodoCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected ITodoToggleData executeCommand(ITodoToggleData data, PersistenceHandle readonlyHandle) {
		data.setUpdatedDateTime(data.getSystemTime());
		ITodoModel todo = daoProvider.getTodoDao().selectById(readonlyHandle, data.getId());
		if (todo == null) {
			this.throwIllegalArgumentException("todo with id " + data.getId() + " does not exist.");
		}
		data.setTodoToBeToggled(todo);
		data.setDone(!todo.getDone());
		this.addSuccessOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



