/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.todo.actions;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.todo.data.ITodoListData;
import com.anfelisa.todo.models.ICategoryModel;
import com.anfelisa.todo.models.ITodoModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetAllTodosAction extends AbstractGetAllTodosAction {

	static final Logger LOG = LoggerFactory.getLogger(GetAllTodosAction.class);

	public GetAllTodosAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected ITodoListData loadDataForGetRequest(ITodoListData data, PersistenceHandle readonlyHandle) {
		ICategoryModel categoryModel = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle, data.getCategoryId());
		if (categoryModel != null) {
			List<ITodoModel> todos = daoProvider.getTodoDao().selectAllOrderedByCreatedDate(readonlyHandle, data.getCategoryId());
			data.setTodoList(todos);
		}
		return data;
	}
	

}



/******* S.D.G. *******/



