/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




package de.acegen;

import org.jdbi.v3.core.Jdbi;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DatabaseHandle {

	static final Logger LOG = LoggerFactory.getLogger(DatabaseHandle.class);

	private PersistenceHandle handle;

	public DatabaseHandle(Jdbi jdbi, CustomAppConfiguration appConfiguration) {
		super();
		this.handle = new PersistenceHandle(jdbi.open().setReadOnly(false));
	}

	synchronized public void beginTransaction() {
		handle.getHandle().begin();
	}

	synchronized public void commitTransaction() {
		handle.getHandle().commit();
	}

	synchronized public void rollbackTransaction() {
		handle.getHandle().rollback();
	}

	synchronized public void close() {
		handle.getHandle().close();
	}

	public PersistenceHandle getHandle() {
		return handle;
	}

	public PersistenceHandle getReadonlyHandle() {
		return handle;
	}

	public PersistenceHandle getTimelineHandle() {
		return handle;
	}

}



/******* S.D.G. *******/



