/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package de.acegen;

public class EventReplayService {
	public static void replayEvent(String eventClass, String json, PersistenceHandle handle, ViewProvider viewProvider) {
		com.anfelisa.todo.events.EventReplayService.replayEvent(eventClass, json, handle, viewProvider);
	}
}



/******* S.D.G. *******/



