/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package de.acegen;

public class EventReplayService {
	public static void replayEvent(String eventClass, String json, PersistenceHandle handle, IDaoProvider daoProvider, ViewProvider viewProvider, CustomAppConfiguration appConfiguration) {
		com.anfelisa.todo.events.EventReplayService.replayEvent(eventClass, json, handle, daoProvider, viewProvider, appConfiguration);
	}
}



/******* S.D.G. *******/



