/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




package com.anfelisa.todo.views;

import com.anfelisa.todo.data.ICategoryData;

import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;

public class CategoryView implements ICategoryView {

	private IDaoProvider daoProvider;
	
	public CategoryView(IDaoProvider daoProvider) {
		super();
		this.daoProvider = daoProvider;
	}

	public void create(ICategoryData data, PersistenceHandle handle) {
		daoProvider.getCategoryDao().insert(handle, data);
	}

}




/******* S.D.G. *******/



