/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.scenarios;

import com.anfelisa.todo.data.DeleteTodoResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class DeleteTodoScenario extends AbstractDeleteTodoScenario {

	

}




/******* S.D.G. *******/



