/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.scenarios;

import com.anfelisa.todo.data.GetTodoResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class GetTodoJsonScenario extends AbstractGetTodoJsonScenario {

	

}




/******* S.D.G. *******/



