/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.get.all.scenarios;

import com.anfelisa.todo.data.GetAllTodosResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class GetAllTodosScenario extends AbstractGetAllTodosScenario {

	

}




/******* S.D.G. *******/



