/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.get.all.scenarios;

public class GetAllTodosScenario extends AbstractGetAllTodosScenario {

	

}




/******* S.D.G. *******/



