/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.get.all.scenarios;

import com.anfelisa.todo.data.GetAllTodosResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class GetManyTodosScenario extends AbstractGetManyTodosScenario {

	@Override
	protected void atLeastTwentyReturned(com.anfelisa.todo.data.GetAllTodosResponse response) {
		assertTrue(response.getTodoList().size() >= 20);
		LOG.info("THEN: atLeastTwentyReturned passed");
	}
	

}




/******* S.D.G. *******/



