/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.create.scenarios;

public class CreateRandomTodoScenario extends AbstractCreateRandomTodoScenario {

	

}




/******* S.D.G. *******/



