/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




package com.anfelisa.todo.models;

public class CategoryDao extends AbstractCategoryDao {
	
}



/******* S.D.G. *******/



