/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.todo.delete.scenarios;

public class DeleteTodoJsonScenario extends AbstractDeleteTodoJsonScenario {

	

}




/******* S.D.G. *******/



